version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
      time: '03:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 99
    versioning-strategy: increase
    ignore:
      - dependency-name: '@babel/core'
        versions:
          - 7.13.1
      - dependency-name: '@emotion/core'
        versions:
          - 11.0.0
      - dependency-name: '@emotion/babel-preset-css-prop'
        versions:
          - 11.0.0
